=== NielsHoffmann/bblock-dcat-ap-nl/build/annotated/bbr/dcat/dcat-ap-nl/dataservice-records/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://geonovum-labs.bbr.dcat.dataservice-records.json",
  "title": "DCAT DataService OGC API record definition",
  "description": "DCAT DataService OGC API record definition",
  "required": [
    "id",
    "conformsTo"
  ],
  "properties": {
    "id": {
      "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordGeoJSON.yaml",
      "x-jsonld-id": "@id"
    },
    "conformsTo": {
      "type": "array",
      "x-jsonld-container": "@set",
      "x-jsonld-id": "http://purl.org/dc/terms/conformsTo",
      "x-jsonld-type": "@id"
    },
    "type": {
      "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordGeoJSON.yaml",
      "x-jsonld-id": "@type"
    },
    "time": {
      "oneOf": [
        {
          "enum": [
            null
          ]
        },
        {
          "type": "object",
          "properties": {
            "date": {
              "type": "string",
              "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
            },
            "timestamp": {
              "type": "string",
              "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
            },
            "interval": {
              "type": "array",
              "minItems": 2,
              "maxItems": 2,
              "items": {
                "oneOf": [
                  {
                    "type": "string",
                    "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
                  },
                  {
                    "type": "string",
                    "pattern": "^\\d{4}-\\d{2}$"
                  },
                  {
                    "type": "string",
                    "pattern": "^\\d{4}$"
                  },
                  {
                    "type": "string",
                    "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
                  },
                  {
                    "type": "string",
                    "pattern": "^T\\d{2}(:\\d{2})?(:\\d{2})?(?:\\.\\d+)?Z$"
                  },
                  {
                    "type": "string",
                    "enum": [
                      ".."
                    ]
                  }
                ]
              }
            },
            "resolution": {
              "type": "string",
              "description": "Minimum time period resolvable in the dataset, as an ISO 8601 duration",
              "pattern": "^(-?)P(?=\\\\d|T\\\\d)(?:(\\\\d+)Y)?(?:(\\\\d+)M)?(?:(\\\\d+)([DW]))?(?:T(?:(\\\\d+)H)?(?:(\\\\d+)M)?(?:(\\\\d+(?:\\\\.\\\\d+)?)S)?)?$"
            }
          }
        }
      ],
      "x-jsonld-id": "http://purl.org/dc/terms/temporal"
    },
    "geometry": {
      "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordGeoJSON.yaml",
      "x-jsonld-id": "https://purl.org/geojson/vocab#geometry",
      "x-jsonld-extra-terms": {
        "coordinates": {
          "x-jsonld-container": "@list",
          "x-jsonld-id": "https://purl.org/geojson/vocab#coordinates"
        }
      }
    },
    "properties": {
      "type": "object",
      "required": [
        "type",
        "title",
        "description",
        "created"
      ],
      "properties": {
        "type": {
          "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordCommonProperties.yaml",
          "x-jsonld-id": "@type"
        },
        "title": {
          "$ref": "#/definitions/MultilingualString",
          "description": "A human-readable name given to the resource.",
          "x-jsonld-container": "@set",
          "x-jsonld-id": "http://purl.org/dc/terms/title"
        },
        "description": {
          "$ref": "#/definitions/MultilingualString",
          "description": "A free-text account of the resource.",
          "x-jsonld-container": "@set",
          "x-jsonld-id": "http://purl.org/dc/terms/description"
        },
        "keywords": {
          "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordCommonProperties.yaml",
          "x-jsonld-container": "@set",
          "x-jsonld-id": "http://www.w3.org/ns/dcat#keyword"
        },
        "themes": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/theme.yaml"
          },
          "x-jsonld-container": "@set",
          "x-jsonld-id": "https://www.opengis.net/def/ogc-api/records/themes"
        }
      },
      "version": {
        "type": "string",
        "description": "The version or edition of a given dataset."
      },
      "externalIds": {
        "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordCommonProperties.yaml"
      },
      "created": {
        "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordCommonProperties.yaml"
      },
      "updated": {
        "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordCommonProperties.yaml"
      },
      "rights": {
        "$ref": "https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordCommonProperties.yaml"
      },
      "x-jsonld-id": "@nest"
    },
    "links": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/Link"
      },
      "x-jsonld-id": "http://www.w3.org/2000/01/rdf-schema#seeAlso",
      "x-jsonld-extra-terms": {
        "hreflang": "http://purl.org/dc/terms/language",
        "length": "http://purl.org/dc/terms/extent"
      }
    }
  },
  "definitions": {
    "Link": {
      "title": "Link object definition",
      "description": "Link object definition including distribution",
      "type": "object",
      "required": [
        "href"
      ],
      "properties": {
        "href": {
          "type": "string",
          "format": "uri",
          "x-jsonld-type": "@id",
          "x-jsonld-id": "http://www.w3.org/ns/oa#hasTarget"
        },
        "rel": {
          "type": "string",
          "x-jsonld-id": "http://www.iana.org/assignments/relation",
          "x-jsonld-type": "@id",
          "x-jsonld-base": "http://www.iana.org/assignments/relation/"
        },
        "type": {
          "type": "string",
          "x-jsonld-id": "@type"
        },
        "title": {
          "type": "string",
          "x-jsonld-container": "@set",
          "x-jsonld-id": "http://purl.org/dc/terms/title"
        },
        "distribution": {
          "type": "object",
          "description": "Available distribution of the dataset via this link.",
          "properties": {
            "title": {
              "$ref": "#/definitions/MultilingualString",
              "x-jsonld-container": "@set",
              "x-jsonld-id": "http://purl.org/dc/terms/title"
            },
            "description": {
              "$ref": "#/definitions/MultilingualString",
              "x-jsonld-container": "@set",
              "x-jsonld-id": "http://purl.org/dc/terms/description"
            },
            "accessURL": {
              "type": "string",
              "format": "uri"
            },
            "downloadURL": {
              "type": "string",
              "format": "uri"
            },
            "format": {
              "type": "string"
            },
            "license": {
              "type": "string",
              "x-jsonld-id": "http://www.w3.org/ns/dcat#license"
            }
          },
          "x-jsonld-id": "http://www.w3.org/ns/dcat#distribution",
          "x-jsonld-type": "@id"
        }
      }
    },
    "LanguageMap": {
      "type": "object",
      "description": "A language-mapped string where keys are BCP 47 language tags and values are the localized strings.",
      "patternProperties": {
        "^[a-zA-Z]{2,8}(-[a-zA-Z0-9]{2,8})*$": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "MultilingualString": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/LanguageMap"
        }
      ]
    }
  },
  "x-jsonld-extra-terms": {
    "Feature": "https://purl.org/geojson/vocab#Feature",
    "FeatureCollection": "https://purl.org/geojson/vocab#FeatureCollection",
    "GeometryCollection": "https://purl.org/geojson/vocab#GeometryCollection",
    "LineString": "https://purl.org/geojson/vocab#LineString",
    "MultiLineString": "https://purl.org/geojson/vocab#MultiLineString",
    "MultiPoint": "https://purl.org/geojson/vocab#MultiPoint",
    "MultiPolygon": "https://purl.org/geojson/vocab#MultiPolygon",
    "Point": "https://purl.org/geojson/vocab#Point",
    "Polygon": "https://purl.org/geojson/vocab#Polygon",
    "features": {
      "x-jsonld-container": "@set",
      "x-jsonld-id": "https://purl.org/geojson/vocab#features"
    },
    "bbox": {
      "x-jsonld-container": "@list",
      "x-jsonld-id": "https://purl.org/geojson/vocab#bbox"
    },
    "linkTemplates": {
      "x-jsonld-context": {
        "rel": {
          "@context": {
            "@base": "http://www.iana.org/assignments/relation/"
          },
          "@id": "http://www.iana.org/assignments/relation",
          "@type": "@id"
        },
        "type": "http://purl.org/dc/terms/format",
        "hreflang": "http://purl.org/dc/terms/language",
        "title": "http://www.w3.org/2000/01/rdf-schema#label",
        "length": "http://purl.org/dc/terms/extent",
        "uriTemplate": {
          "@type": "http://www.w3.org/2001/XMLSchema#string",
          "@id": "https://www.opengis.net/def/ogc-api/records/uriTemplate"
        },
        "varBase": "https://www.opengis.net/def/ogc-api/records/varBase",
        "variables": {
          "@id": "https://www.opengis.net/def/ogc-api/records/hasVariable",
          "@container": "@index",
          "@index": "http://purl.org/dc/terms/identifier"
        }
      },
      "x-jsonld-id": "https://www.opengis.net/def/ogc-api/records/hasLinkTemplate"
    },
    "created": "http://purl.org/dc/terms/created",
    "updated": "http://purl.org/dc/terms/modified",
    "language": {
      "x-jsonld-id": "https://www.opengis.net/def/ogc-api/records/language",
      "x-jsonld-context": {
        "code": "https://www.opengis.net/def/ogc-api/records/languageCode",
        "name": "http://www.w3.org/2004/02/skos/core#prefLabel"
      }
    },
    "languages": {
      "x-jsonld-container": "@set",
      "x-jsonld-id": "https://www.opengis.net/def/ogc-api/records/languages",
      "x-jsonld-context": {
        "code": "https://www.opengis.net/def/ogc-api/records/languageCode",
        "name": "http://www.w3.org/2004/02/skos/core#prefLabel"
      }
    },
    "resourceLanguages": {
      "x-jsonld-container": "@set",
      "x-jsonld-id": "https://www.opengis.net/def/ogc-api/records/resourceLanguages",
      "x-jsonld-context": {
        "code": "https://www.opengis.net/def/ogc-api/records/languageCode",
        "name": "http://www.w3.org/2004/02/skos/core#prefLabel"
      }
    },
    "externalIds": {
      "x-jsonld-container": "@set",
      "x-jsonld-id": "https://www.opengis.net/def/ogc-api/records/scopedIdentifier",
      "x-jsonld-context": {
        "scheme": "https://www.opengis.net/def/ogc-api/records/scheme",
        "value": "https://www.opengis.net/def/ogc-api/records/id"
      }
    },
    "formats": {
      "x-jsonld-id": "https://www.opengis.net/def/ogc-api/records/format",
      "x-jsonld-context": {
        "name": "https://www.opengis.net/def/ogc-api/records/name",
        "mediaType": "https://www.opengis.net/def/ogc-api/records/mediaType"
      },
      "x-jsonld-container": "@set",
      "x-jsonld-type": "@id"
    },
    "contacts": {
      "x-jsonld-container": "@set",
      "x-jsonld-id": "http://www.w3.org/ns/dcat#contactPoint",
      "x-jsonld-type": "@id"
    },
    "accessrights": "http://purl.org/dc/terms/accessRights",
    "variables": {
      "x-jsonld-container": "@id",
      "x-jsonld-id": "https://www.opengis.net/def/ogc-api/records/hasVariable",
      "x-jsonld-context": {
        "@base": "http://example.com/variables/",
        "@vocab": "https://www.opengis.net/def/ogc-api/records/"
      }
    },
    "rights": "http://www.w3.org/ns/dcat#rights"
  },
  "x-jsonld-prefixes": {
    "geojson": "https://purl.org/geojson/vocab#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "dct": "http://purl.org/dc/terms/",
    "dcat": "http://www.w3.org/ns/dcat#",
    "rec": "https://www.opengis.net/def/ogc-api/records/",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "thns": "https://w3id.org/ogc/stac/themes/",
    "oa": "http://www.w3.org/ns/oa#",
    "owl": "http://www.w3.org/2002/07/owl#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "w3ctime": "http://www.w3.org/2006/time#",
    "dctype": "http://purl.org/dc/dcmitype/",
    "vcard": "http://www.w3.org/2006/vcard/ns#",
    "prov": "http://www.w3.org/ns/prov#",
    "foaf": "http://xmlns.com/foaf/0.1/"
  }
}

=== NielsHoffmann/bblock-dcat-ap-nl/build/tests/bbr/dcat/dcat-dataset-records/example_1_1.json
{
  "id": "7b03a8de-5d0c-11ee-8a7e-3ce9f7462b83",
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-records-1/1.0/req/record-core"
  ],
  "type": "Feature",
  "time": {
    "interval": [
      "2024-09-30",
      "9999-12-31"
    ],
    "resolution": "P1D"
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          2.4807,
          53.7187
        ],
        [
          7.9685,
          53.7187
        ],
        [
          7.9685,
          50.6058
        ],
        [
          2.4807,
          50.6058
        ],
        [
          2.4807,
          53.7187
        ]
      ]
    ]
  },
  "properties": {
    "created": "2024-09-30",
    "updated": "2024-12-06T09:49:52Z",
    "type": "dataset",
    "title": "Bomen",
    "description": "Subset van bomen in de omgeving van Sloten (Amsterdam)",
    "providers": [
      {
        "contactInfo": {
          "address": {
            "office": {}
          },
          "email": {
            "office": "opendata@amsterdam.nl"
          }
        },
        "name": null,
        "roles": [
          {
            "name": "pointOfContact"
          }
        ]
      }
    ],
    "externalIds": [
      {
        "scheme": "default",
        "value": "7b03a8de-5d0c-11ee-8a7e-3ce9f7462b83"
      }
    ],
    "themes": [
      {
        "concepts": [
          {
            "id": "Boom",
            "url": "https://definities.geostandaarden.nl/ibro/id/begrip/boom"
          },
          {
            "id": "Park",
            "url": "https://definities.geostandaarden.nl/ibro/id/begrip/park"
          }
        ],
        "scheme": "https://definities.geostandaarden.nl/ibro/nl/"
      }
    ]
  },
  "links": [
    {
      "href": "http://localhost:5000/collections/bomen",
      "rel": "access",
      "title": "Bomen",
      "type": "OGC API Features",
      "distribution": {
        "type": "dcat:Distribution",
        "title": {
          "nl": "Bomen (OGC API Features)"
        },
        "description": {
          "nl": "API"
        },
        "license": "http://creativecommons.org/publicdomain/mark/1.0/deed.nl"
      }
    }
  ]
}
